feat: add doubleclick keyword to Buttons class
imbus/robotframework-PlatynUI pull request #13
Opened 2024-11-05 18:51 UTC by zhajjhassan

This commit adds a new keyword, `doubleclick`, to the `Buttons` class in the `buttons.py` file.

2024-11-07 08:05 UTC, Noordsestern requested changes

2024-11-07 08:05 UTC, Noordsestern commented on src/PlatynUI/keywords/buttons.py
> +    def doubleclick(self, element: Element) -> None:
Ich glaube, das zusammengesetzte Wort "Doppelklick" ist ein deutsches Konstrukt. im englischen müsste es "double click" sein. also:

```
def double_click(self, element: Element) -> None:
```

2024-11-07 08:05 UTC, Noordsestern commented on tests/robot/first.robot
> +    Doubleclick    ${calculator.n1}
`Double Click`

2024-11-08 08:19 UTC, Noordsestern approved these changes
lgtm

2025-01-31 11:19 UTC, zhajjhassan commented
Already implemented!

2025-01-31 11:19 UTC, closed without merging